cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.CartDetail, name='CartDetail'),
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
]

shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.ProductList, name='ProductList'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.ProductList, name='ProductListByCategory'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ProductDetail, name='ProductDetail')
]

untitled/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from shop import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^contact/', views.Contacts, name='Contacts'),
    url(r'^', include('shop.urls', namespace='shop'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.core.urlresolvers import reverse


# Модель категории
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name='Имя')
    slug = models.SlugField(max_length=200, db_index=True, unique=True)


    class Meta:
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:ProductListByCategory', args=[self.slug])

# Модель города
class City(models.Model):
    namecity = models.CharField(max_length=20, db_index=True, verbose_name='город')
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ['namecity']
        verbose_name = 'Город'
        verbose_name_plural = 'Города'

    def __str__(self):
        return self.namecity

# Модель продукта
class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', verbose_name="Категория")
    city = models.ForeignKey(City, related_name='items', verbose_name="Город")
    name = models.CharField(max_length=200, db_index=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/', blank=True, verbose_name="Изображение товара")
    description = models.TextField(blank=True, verbose_name="Описание")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    stock = models.PositiveIntegerField(verbose_name="На складе")
    available = models.BooleanField(default=True, verbose_name="Доступен")
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлен')

    class Meta:
        ordering = ['name']
        index_together = [
            ['id', 'slug']
        ]
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:ProductDetail', args=[self.id, self.slug])


class Contact(models.Model):
    title = models.CharField(max_length=200, db_index=True, verbose_name="Название")
    contact = models.TextField(blank=True, db_index=True, verbose_name='Контакты')
    imagecontact = models.ImageField(upload_to='products/%Y/%m/%d/', blank=True, verbose_name="Изображение")

    class Meta:
        ordering = ['contact']
        verbose_name = 'Контакт'
        verbose_name_plural = 'Контакты'

    def __str__(self):
        return self.contact

shop/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from .models import Category, Product, Contact
from cart.forms import CartAddProductForm


# Create your views here.


# Страница с товарами
def ProductList(request, category_slug='moskva'):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {
        'category': category,
        'categories': categories,
        'products': products
    })


# Страница товара
def ProductDetail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render_to_response('shop/product/detail.html',
                              {'product': product,
                               'cart_product_form': cart_product_form})


def Contacts(request):
    contacts = Contact.objects.all()
    return render_to_response('shop/product/contact.html', {'contacts': contacts})

templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>

  <!-- Styles -->
  <link rel="stylesheet" href="{% static "shop/css/bootstrap.min.css" %}">
  <link rel="stylesheet" href="{% static "shop/css/style.css" %}">
</head>
<body>
{% csrf_token %}
  <section id="header">
    <div class="top container">

    </div>
    <div class="top-bl">
      <div class="container">
        <div class="cart">
          {% with total_items=cart|length %}
            {% if cart|length > 0 %}
              Ваша корзина:
              <a href="{% url "cart:CartDetail" %}">
                {{ total_items }} тов. {{ cart.get_total_price }} руб.
              </a>
            {% else %}
              Корзина пустая
            {% endif %}
          {% endwith %}
        </div>
      </div>
    </div>
  </section>
  <section id="content row" class="container">
    {% block content %}{% endblock %}
  </section>
</body>
</html>

templates/shop/base2.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8" />
    <meta  http-equiv="x-ua-compatible" content="ie=edge">
    <title>{{ title }} - Shop job</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/css/bootstrap.css' %}" />
{% comment %}
    <link rel="stylesheet" type="text/css" href="{% static 'shop/css/bootstrap.min.css' %}" />
{% endcomment %}
    <link rel="stylesheet" type="text/css" href="{% static "shop/css/style.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "shop/css/jqsimplemenu.css" %}">
    <script src="{% static 'shop/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'shop/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'shop/scripts/respond.js' %}"></script>
    <style>

    </style>

    {% block head %}

     {% endblock %}

<body>

   <div class="navbar navbar-inverse ">
            <div class="logo">
                <img class="logo" src="{% static "/shop/image/logoEuroplan.png" %}"/>
            </div>
       <div>
            <a class="auth" href="/admin/">Личный кабинет</a>
       </div>
        <div class="container">

{% comment %}
     <div>
         <ul  class="nav navbar-nav ">
      <li class="dropdown">
        <a class="dropdown-toggle pull-right" data-toggle="dropdown" data-target="#"  href="{% url 'shop:ProductList' %}">Меню <b class="caret"></b></a>
        <ul id="menu1" class="dropdown-menu">
          <li><a href="#">Действие</a></li>
          <li><a href="#">Другое действие</a></li>
          <li><a href="#">Ссылка</a></li>
          <li class="divider"></li>
          <li><a href="#">Отделенная ссылка</a></li>
        </ul>
      </li>
    </ul></div>

{% endcomment %}



            <div>


                <ul class="nav navbar-nav">

                    <li><a href="{% url 'shop:ProductList' %}">Твои товары</a></li>
                    <li><a href="{% url 'Contacts' %}">Контакты</a></li>
                    <li><a href="/admin/">Авторизация</a></li>
                    <li>

                    {% with total_items=cart|length %}
                    {% if cart|length > 0 %}

                        <li><a href="{% url "cart:CartDetail" %}">
                        В корзине {{ total_items }} тов. {{ cart.get_total_price }} руб.
                        </a></li>
            {% else %}
              <li><a href="{% url "cart:CartDetail" %}"> Корзина</a></li>
            {% endif %}
          {% endwith %}
                </ul>
            </div>
        </div>
    </div>

    {% block content %}

    {% endblock %}



    <div class="container body-content">
        <hr/>
        <footer>
            <p>Настоящий перечень товаров (имущества) представлен для целей ознакомления работников АО «ЛК «Европлан», ОГРН 1177746637584 (далее – Общество) с возможностью приобретения в собственность бывшего в употреблении имущества Общества по договорам купли-продажи, заключаемым Обществом (в качестве продавца) и работниками Общества (в качестве покупателей), составляемых в простой письменной форме. Настоящее предложение об ознакомлении работников Общества с возможностью приобретения в собственность имущества Общества не является офертой. Правила о дистанционном способе продажи товара (имущества) не применяются.</p>
            <p>&copy; {{ year }} - Shop by Andrew Skvortsov</p>
        </footer>
    </div>

{% block scripts %}

{% endblock %}

</body>
</html>